site_name: Brive docs

docs_dir: md
site_dir: docs
use_directory_urls: false

theme:
  name: material
  logo: assets/logo.png
  palette:
    # scheme: slate
    # scheme: default
    # primary: indigo

    - scheme: default
      toggle:
        icon: material/brightness-7 


        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.code.copy
 
markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition